### ISSUE TITLE
Add mising docker compose files

### ISSUE THREAD

**Issue by richard-mauri** [pmihaylovcom/go-elk-tutorial#1]

**Comment by presmihaylov** [comment]
Hey @richard-mauri this repo is meant as a starting point for [this article](https://pmihaylov.com/go-service-with-elk/).

The docker-compose files & elk config files are added whilst doing the tutorial.

If you, however, only want the final setup without going through the tutorial, you can check out [this branch of my tutorials repo](https://github.com/preslavmihaylov/tutorials/tree/kibana-dashboard-tutorial).

It's part of [this article/tutorial](https://pmihaylov.com/kibana-dashboard-tutorial/) which depends on using the files added as part of the tutorial in this repo.
